const userTypes = {
  SET_USERS: "SET_USERS",
  SET_USER_MESSAGES: "SET_USER_MESSAGES",
  SET_SELECTED_USER: "SET_SELECTED_USER",
  ADD_MESSAGE: "ADD_MESSAGE",
  ADD_REACTION: "ADD_REACTION",
};

export default userTypes;
